### ISSUE TITLE
Some graphics in README.md are unavailable

### ISSUE THREAD

**Issue by PhilipSharman** [CezaryKopacz/CKWaveCollectionViewTransition#1]
In the readme, the following graphics give me "Access denied" errors when I view the readme offline:
- https://bitbucket.org/repo/bdbxyL/images/476354846-object.jpg
- https://bitbucket.org/repo/bdbxyL/images/3022245965-objectCustomClass.jpg
- https://bitbucket.org/repo/bdbxyL/images/3403085542-navigationControllerDelegateObject.jpg

And the following graphics give me "Not Found" errors when I view the readme online:
- https://camo.githubusercontent.com/5ec21bb2c56b67eb32face9cefeeb240ec0c95d0/68747470733a2f2f6269746275636b65742e6f72672f7265706f2f62646278794c2f696d616765732f3437363335343834362d6f626a6563742e6a7067
- https://camo.githubusercontent.com/928dd63dfdaacbda36e429bb31f775cf32edcb07/68747470733a2f2f6269746275636b65742e6f72672f7265706f2f62646278794c2f696d616765732f333032323234353936352d6f626a656374437573746f6d436c6173732e6a7067
- https://camo.githubusercontent.com/928dd63dfdaacbda36e429bb31f775cf32edcb07/68747470733a2f2f6269746275636b65742e6f72672f7265706f2f62646278794c2f696d616765732f333032323234353936352d6f626a656374437573746f6d436c6173732e6a7067

(It is the same three graphics, under "Usage".)

Thanks.  (This is a lovely library!)

**Comment by CezaryKopacz** [comment]
Moved images to GitHub repo.
