### ISSUE TITLE
Update for Swift 2

### ISSUE THREAD

**Issue by hipwelljo** [CezaryKopacz/CKWaveCollectionViewTransition#2]
:)

**Comment by derdida** [comment]
that would be great!

**Comment by michaelbina** [comment]
Any movement on this by chance?

**Comment by CezaryKopacz** [comment]
Just updated for swift 2.1

**Comment by michaelbina** [comment]
I'm not sure if this is still related, but I just downloaded with your new commits and these are the errors I'm seeing in Xcode 7.2 beta (7C62b):

<img width="375" alt="screen shot 2015-12-13 at 5 04 44 am" src="https://cloud.githubusercontent.com/assets/528845/11767110/560c6f4e-a157-11e5-9650-2033163d90ec.png">

**Comment by CezaryKopacz** [comment]
i just checked this on XCode 7.2 and everything is fine
