### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by scibas** [CezaryKopacz/CKWaveCollectionViewTransition#3]
IMO, documentation should mention that you need to set `self.selectedIndexPath = indexPath;` in `-collectionView:didSelectItemAtIndexPath:` It may save debugging time for others. 
You could also make an assertion in code (line ~247) when `destinationCollectionViewController.selectedIndexPath` is nil with some descriptive comment. 

Good job anyway!

**Comment by CezaryKopacz** [comment]
Thanks for the tip!
